apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openai-autosync-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ajmal-MP/openai-helm
    # chart: 
    path: helm-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true